codecov:
  branch: master


coverage:
  status:
    patch: false

  range: 40..90     # First number represents red, and second represents green
                    # (default is 70..100)


# Ignoring Paths
# --------------
# which folders/files to ignore
ignore:
  - svh-gbif-datamodel/src/main/java/se/nrm/bas/svh/gbif/datamodel/
